### ISSUE TITLE
build failure,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [zeckalpha/kyle.marek-spartz.org#2]
hi.

root@AR:/usr/local/kyle.marek-spartz.org# .stack-work/dist/i386-linux/Cabal-1.22.4.0/build/site/site build

it shows:
[ERROR] Hakyll.Core.Compiler.Require.load: css/combined.css (snapshot _final) was not found in the cache, the cache might be corrupted or the item you are referring to might not exist
root@AR:/usr/local/kyle.marek-spartz.org# ls
404.md        colophon.md      kyle-marek-spartz-org.cabal  README.md
about.md      css          LICENSE.md           robots.txt
build_css.sh      echo_sitemap.sh  new_post.py          salem
build_cv.sh   favicon.ico      now.md           _site
build_sitemap.sh  files        posts            site.hs
_cache        images       presentations        stack.yaml
check.sh      keybase.txt      publications         templates
root@AR:/usr/local/kyle.marek-spartz.org#
root@AR:/usr/local/kyle.marek-spartz.org# ls css
default.css  site.css  syntax.css
root@AR:/usr/local/kyle.marek-spartz.org#

indeed there is no combined.css file in /usr/local/kyle.marek-spartz.org/css/,

how to fix it?
thank you.

**Comment by kmarekspartz** [comment]
I run `site deploy`, which runs the deployCommand from the site.hs. You probably do not want to do this, as it will try to deploy the website... Instead, use the portions of https://github.com/zeckalpha/kyle.marek-spartz.org/blob/master/site.hs#L250 that you need, probably just `./build_css.sh && pushd presentations && ./build.sh && popd && ./build_cv.sh && ./build_sitemap.sh`

**Comment by kmarekspartz** [comment]
Closing, feel free to reopen if that doesn't work.

**Comment by luckypoem** [comment]
oh,i see.

root@AR:/usr/local/kyle.marek-spartz.org# cat build_css.sh
cat css/syntax.css css/default.css css/site.css > css/combined.css
root@AR:/usr/local/kyle.marek-spartz.org# cat css/syntax.css css/default.css css/site.css > css/combined.css
root@AR:/usr/local/kyle.marek-spartz.org# .stack-work/dist/i386-linux/Cabal-1.22.4.0/build/site/site build

this time,it succeeded
